apiVersion: db-operator.kubemaster.com/v1alpha1
kind: DbServer
metadata:
  name: example-host
spec:
  address: postgres
  port: 5432
  user_name: postgres
  secret_name: postgres
  server_type: postgres
  options:
    sslmode: require

--- 

apiVersion: db-operator.kubemaster.com/v1alpha1
kind: DbServer
metadata:
  name: example-host-mysql
spec:
  address: mysql
  port: 3306
  user_name: root
  secret_name: mysql
  server_type: mysql