apiVersion: v1
kind: Secret
metadata:
  name: example-user-secret
data:
  password: YmxhCg==

---

apiVersion: db-operator.kubemaster.com/v1alpha1
kind: User
metadata:
  name: example-user
spec:
  db_server_name: example-host
  user_name: sjuul
  secret_name: example-user-secret


---

apiVersion: db-operator.kubemaster.com/v1alpha1
kind: User
metadata:
  name: example-user-2
spec:
  db_server_name: example-host
  user_name: sjuul2
  secret_name: example-user-secret