include:
  - project: 'kevineu/devex/ci-cd-pipelines'
    file: '/gitlab-utils/.gitlab-ci-globals.yml'
  - project: 'kevineu/appsec/sast-configs'
    file: '/Semgrep.gitlab-ci.yml'
  - project: 'kevineu/devex/ci-cd-pipelines'
    file: '/gitlab-utils/.gitlab-ci-build-push.yml'
    ref: 'no-create-workspace-dir'

.rules:
  - &on-merge-request
    if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  - &on-push-to-main
    if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"

.deploy_trigger:
  trigger:
    include:
      - local: .gitlab-ci-deploy.yml

.dev_trigger:
  extends: .deploy_trigger
  stage: deploy_dev

variables:
  APP_NAME: db-operator
  KUBERNETES_CPU_REQUEST: "1"
  KUBERNETES_CPU_LIMIT: "4"
  KUBERNETES_MEMORY_REQUEST: "1Gi"
  KUBERNETES_MEMORY_LIMIT: "4Gi"
  KUBERNETES_SERVICE_CPU_REQUEST: "1"
  KUBERNETES_SERVICE_CPU_LIMIT: "4"
  KUBERNETES_SERVICE_MEMORY_REQUEST: "1Gi"
  KUBERNETES_SERVICE_MEMORY_LIMIT: "6Gi"
  KUBERNETES_HELPER_CPU_REQUEST: "1"
  KUBERNETES_HELPER_CPU_LIMIT: "2"
  KUBERNETES_HELPER_MEMORY_REQUEST: "1Gi"
  KUBERNETES_HELPER_MEMORY_LIMIT: "4Gi"
   
stages:
  # - build-ci-image
  - test

test image:
  services:
  - name: docker:dind
    command: [ "--tls=false" ]
  stage: test
  tags: [ "k8s-runner" ]
  image:
    # name: $CI_REGISTRY_IMAGE:cilatest
    name: golang:1.20-buster
    pull_policy: if-not-present
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - apt-get update && apt-get install -y ca-certificates curl gnupg lsb-release
    - mkdir -m 0755 -p /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - apt-get update && apt-get install -y docker-ce-cli
    - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
    - chmod +x ./kind
    - mv ./kind /usr/local/bin/kind
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - curl -Lo ./kuttl https://github.com/kudobuilder/kuttl/releases/download/v0.15.0/kubectl-kuttl_0.15.0_darwin_x86_64
    - chmod +x ./kuttl
    - mv ./kuttl /usr/local/bin/kuttl
    - make kind-cluster
    - make kuttl-test
    - go test ./... -v -short
  after_script:
    - kind delete cluster
  rules:
    - *on-merge-request
    - *on-push-to-main

build:
  image: docker:20.10.16
  stage: build-ci-image
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:cilatest .
    - docker push $CI_REGISTRY_IMAGE:cilatest
  only:
    changes:
      - Dockerfile.ci