apiVersion: kuttl.dev/v1beta1
kind: TestSuite
name: MySql
testDirs:
- ./tests/mysql
manifestDirs:
- ./tests/mysql-manifests/
# kindConfig: tests/kind-config.yaml
# startKIND: true
# startControlPlane: true
kindContainers:
- library/mysql:latest
# we're sharing the database, in order to have predictable state we don't do parallel tests
parallel: 1
artifactsDir: ./tests/outputs
kindNodeCache: true