# permissions for end users to view backupcronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: backupcronjob-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: db-operator
    app.kubernetes.io/part-of: db-operator
    app.kubernetes.io/managed-by: kustomize
  name: backupcronjob-viewer-role
rules:
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - backupcronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - backupcronjobs/status
  verbs:
  - get
