---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - backupcronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - backupcronjobs/finalizers
  verbs:
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - backupcronjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - backupjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - backupjobs/finalizers
  verbs:
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - backupjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - backuptargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - backuptargets/finalizers
  verbs:
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - backuptargets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - cockroachdbbackupjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - cockroachdbbackupjobs/finalizers
  verbs:
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - cockroachdbbackupjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbcopycronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbcopycronjobs/finalizers
  verbs:
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbcopycronjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbcopyjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbcopyjobs/finalizers
  verbs:
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbcopyjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbs/finalizers
  verbs:
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbservers/finalizers
  verbs:
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - restorecronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - restorecronjobs/finalizers
  verbs:
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - restorecronjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - restorejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - restorejobs/finalizers
  verbs:
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - restorejobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - restoretargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - restoretargets/finalizers
  verbs:
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - restoretargets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - s3storages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - s3storages/finalizers
  verbs:
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - s3storages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - schemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - schemas/finalizers
  verbs:
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - schemas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
