# permissions for end users to edit schemas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: schema-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: db-operator
    app.kubernetes.io/part-of: db-operator
    app.kubernetes.io/managed-by: kustomize
  name: schema-editor-role
rules:
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - schemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - schemas/status
  verbs:
  - get
