apiVersion: db-operator.kubemaster.com/v1alpha1
kind: BackupTarget
metadata:
  labels:
    app.kubernetes.io/name: backuptarget
    app.kubernetes.io/instance: backuptarget-sample
    app.kubernetes.io/part-of: db-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: db-operator
  name: backuptarget-sample
spec:
  # TODO(user): Add fields here
