apiVersion: db-operator.kubemaster.com/v1alpha1
kind: Db
metadata:
  labels:
    app.kubernetes.io/name: db
    app.kubernetes.io/instance: db-sample
    app.kubernetes.io/part-of: db-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: db-operator
  name: db-sample
spec:
  # TODO(user): Add fields here
