{{- range .Values.BackupJobs }}
apiVersion: db-operator.kubemaster.com/v1alpha1
kind: BackupJob
metadata:
  name: {{ quote .name }}
spec:
  backup_target: {{ quote .backup_target }}
  service_account: {{ quote .service_account}}
---
{{ end -}}