{{- range .Values.DbCopyCronJobs }}
apiVersion: db-operator.kubemaster.com/v1alpha1
kind: DbCopyCronJob
metadata:
  name: {{ quote .name }}
spec:
  from_db_name: {{ quote .from_db_name }}
  to_db_name: {{ quote .to_db_name }}
  interval: {{ quote .interval }}
  suspend: {{ .suspend }}
  service_account: {{ quote .service_account}}
---
{{ end -}}