{{- range .Values.DbServers }}
apiVersion: db-operator.kubemaster.com/v1alpha1
kind: DbServer
metadata:
  name: {{ quote .name }}
spec:
  port: {{ .port }}
  user_name: {{ quote .user_name}}
  secret_name: {{ quote .secret_name }}
  server_type: {{ quote .server_type }}
  address: {{ quote .address }}
  {{- if .options }}
  options: 
{{ .options | toYaml | nindent 4 }}
  {{- end }}
---
{{ end -}}