{{- range .Values.RestoreJobs }}
apiVersion: db-operator.kubemaster.com/v1alpha1
kind: RestoreJob
metadata:
  name: {{ quote .name }}
spec:
  restore_target: {{ quote .restore_target }}
  service_account: {{ quote .service_account}}
---
{{ end -}}