apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "db-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: db-operator
    app.kubernetes.io/part-of: db-operator
  {{- include "db-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}